image: docker:latest
services:
  - docker:dind

stages:
  - clean
  - assemble
  - test

clean:
  image: gradle:latest
  stage: clean
  script:
    - gradle clean
  artifacts:
    paths:
      - build/libs/*.jar

build:
  image: gradle:latest
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

test:
  image: gradle:latest
  stage: test
  script:
    - gradle test
  artifacts:
    paths:
      - build/libs/*.jar  

assemble:
  image: gradle:latest
  stage: assemble
  script:
    - gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar
      
after_script:
  - echo "End CI"
